module.exports = {
  MODELS: {
    USER: "user",
    LANGUAGE: "language",
    STATE: "state",
    CATEGORY: "category",
    BUSINESS: "business",
    SEARCH: "search",
    PROFILE_CLICK: "profile-clicks",
    MEDIA: "media",
  },
  VERIFY_CODE_SOURCE: {
    EMAIL_VERIFICATION: "EMAIL_VERIFICATION",
    FORGOT_PASSWORD: "FORGOT_PASSWORD",
  },
  SEARCH_STATUS: {
    ACTIVE: "ACTIVE",
    DELETED: "DELETED",
  },
  UserType: {
    INDIVIDUAL: "INDIVIDUAL",
    BUSINESS: "BUSINESS",
    PROVIDER: "PROVIDER",
  },
  USER_Type: {
    INDIVIDUAL: "INDIVIDUAL",
    BUSINESS: "BUSINESS",
    PROVIDER: "PROVIDER",
  },
  DESIGNATION_TYPE: {
    PARTNER: "PARTNER",
    OF_COUNSEL: "OF_COUNSEL",
    ASSOCIATE: "ASSOCIATE",
    SOLO_PRACTITIONER: "SOLO_PRACTITIONER",
    OTHER: "OTHER",
  },
  BILLING_STRUCTURE: {
    PER_HOUR: "PER_HOUR",
    ON_CONTINGENCY: "ON_CONTINGENCY",
    FIXED_FEE: "FIXED_FEE",
  },
  REPRESENT_TYPE: {
    INDIVIDUAL: "INDIVIDUAL",
    COMPANIES: "COMPANIES",
  },
  PROFICIENCY: {
    NATIVE: "NATIVE",
    FLUENT: "FLUENT",
    INTERMEDIATE: "INTERMEDIATE",
    BEGINNER: "BEGINNER",
  },
  OFFICE_TYPE: {
    PHYSICAL: "PHYSICAL",
    VIRTUAL: "VIRTUAL",
  },
  ADDRESS_TYPE: {
    REGISTERED: "REGISTERED",
    BUSINESS_HQ: "BUSINESS_HQ",
    AGENT: "AGENT",
  },
  EMAIL_SUBJECTS: {
    EMAIL_VERIFICATION: "Lawfirm - Email Verification",
  },
  BUSINESS_TYPE: {
    LLC: "LLC",
    LLP: "LLP",
    LLLP: "LLLP",
    CORPORATION: "CORPORATION",
    PARTNERSHIP: "PARTNERSHIP",
    PROFESSIONAL: "PROFESSIONAL",
  },
  BUSINESS_STATUS: {
    ACTIVE: "ACTIVE",
    DELETED: "DELETED",
  },
  SEARCH_KIND: {
    TEXT: "TEXT",
    CATEGORY: "CATEGORY",
  },
  SUBSCRIPTION_PACKAGES: {
    STANDARD: "STANDARD",
    PREMIUM: "PREMIUM",
  },
};
